# Generated by Django 4.0.5 on 2022-07-06 15:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('lms', tinymce.models.HTMLField()),
                ('lad', tinymce.models.HTMLField()),
                ('ramus', tinymce.models.HTMLField(blank=True, default='dfsdafsdfdsfsafsa', null=True)),
                ('lcx', tinymce.models.HTMLField()),
                ('rca', tinymce.models.HTMLField()),
                ('result_angio', models.CharField(max_length=50)),
                ('recommendation_angio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCI_desc', tinymce.models.HTMLField()),
                ('result_pci', models.CharField(max_length=100)),
                ('recommdendation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(max_length=20)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=20)),
                ('cnic', models.IntegerField()),
                ('indication', models.CharField(max_length=100)),
                ('visit_number', models.IntegerField()),
                ('Date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('angio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.angio')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.operator')),
                ('pci', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.pci')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_app.procedure')),
            ],
        ),
    ]
