# Generated by Django 4.0.5 on 2022-07-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pci',
            old_name='PCI_desc',
            new_name='pci_desc',
        ),
    ]
