# Generated by Django 4.0.5 on 2022-11-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_remove_patient_procedure_pci_pci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='angio',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pci',
        ),
        migrations.RemoveField(
            model_name='pci',
            name='pci',
        ),
        migrations.AddField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main_app.procedure'),
        ),
        migrations.AddField(
            model_name='pci',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.patient'),
        ),
    ]
