# Generated by Django 4.0.5 on 2022-07-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_rename_pci_desc_pci_pci_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pci',
            old_name='recommdendation',
            new_name='recommendation',
        ),
    ]
