# Generated by Django 4.0.5 on 2022-07-15 13:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_rename_recommdendation_pci_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angio',
            name='lad',
            field=models.TextField(default='Proximal: Normal, Mid: Normal </br> Distal:Normal'),
        ),
        migrations.AlterField(
            model_name='angio',
            name='lcx',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='angio',
            name='lms',
            field=models.TextField(default='Normal'),
        ),
        migrations.AlterField(
            model_name='angio',
            name='ramus',
            field=models.TextField(blank=True, default='Not Present', null=True),
        ),
        migrations.AlterField(
            model_name='angio',
            name='rca',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='angio',
            name='text',
            field=tinymce.models.HTMLField(verbose_name=' Right Radial Artery entered with Seldinger technique using  6F sheath. Diagnostic Catheter TIG II 5F used for LCA & JR-4 5F used for RCA. Standard views recorded. Pressure homeostasis achieved.'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='angio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.angio'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.pci'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main_app.procedure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pci',
            name='pci_desc',
            field=tinymce.models.HTMLField(default='Right Radial access used to engage LAD with Guiding Catheter JL-4 6F. Injection given lesion identified in LAD. BMW wire 0.014x190 cm wire used to cross the lesion in LAD. Pre dilatation done with Compliant 2.0x10 mm Balloon at 10 atm. Firehawk 3.0x18mm (DES) stent deployed in Proximal LAD inflated at 14 atm. Successful PCI done to LAD. TIMI grade III flow obtained with no immediate complications.'),
        ),
    ]
