# Generated by Django 4.0.5 on 2022-11-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_remove_patient_angio_remove_patient_pci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pci',
            name='pid',
        ),
        migrations.AddField(
            model_name='patient',
            name='angio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.angio'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.pci'),
        ),
    ]
