# Generated by Django 4.0.5 on 2022-07-15 13:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_alter_angio_lad_alter_angio_lcx_alter_angio_lms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angio',
            name='text',
            field=tinymce.models.HTMLField(default=' Right Radial Artery entered with Seldinger technique using  6F sheath. Diagnostic Catheter TIG II 5F used for LCA & JR-4 5F used for RCA. Standard views recorded. Pressure homeostasis achieved.'),
        ),
    ]
