# Generated by Django 4.0.5 on 2022-12-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0004_remove_pci_pid_patient_angio_patient_pci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_app.procedure'),
        ),
    ]
