# Generated by Django 4.0.5 on 2022-12-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0005_alter_patient_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angio',
            name='recommendation_angio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='angio',
            name='result_angio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='operator',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pci',
            name='result_pci',
            field=models.CharField(default=' Successful PCI done to', max_length=200),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_type',
            field=models.CharField(max_length=50),
        ),
    ]
