# Generated by Django 4.0.5 on 2022-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0006_alter_pci_result_pci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pci',
            name='recommendation',
            field=models.CharField(default='Dual Antiplatelet therapy', max_length=200),
        ),
    ]
