# Generated by Django 4.0.5 on 2022-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0009_alter_angio_lad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angio',
            name='lcx',
            field=models.TextField(default='Proximal: Normal </br> Distal:Normal'),
        ),
        migrations.AlterField(
            model_name='angio',
            name='rca',
            field=models.TextField(default='Proximal: Normal </br> Mid: Normal </br> Distal:Normal'),
        ),
    ]
